---
abstract: 'Alien wrapper for zlib'
author:
  - 'Johanna Amann <johanna@icir.org>'
build_requires: {}
configure_requires:
  Alien::Base::ModuleBuild: '0.025'
  Module::Build: '0.38'
  Test::More: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4222, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-zlib-Static
provides:
  Alien::zlib::Static:
    file: lib/Alien/zlib/Static.pm
    version: '0.10'
requires:
  Alien::Base: '0.025'
  File::ShareDir: '1.00'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ollyg/alien-zlib-static/issues
  homepage: https://github.com/ollyg/alien-zlib-static
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ollyg/alien-zlib-static.git
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.011'
